import Head from 'next/head'
import { motion as m } from 'framer-motion'
import { container, item } from '../animations';

export default function Home() {
  return (
    <m.div 
    initial={{ y: "100%" }}
    animate={{ y: "0%" }}
    transition={{ duration: 0.75, ease: "easeOut" }}
    exit={{ opacity: 1, }}
    className="text-grey-900 absolute top-0 left-0 w-full h-full bg-orange-100 lg:px-48 px-16"
    >
      <Head>
        <title>Angel Ramirez | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='my-96 p-1 overflow-hidden'>
          <m.h1 animate={{ y: 0 }} 
                initial={{ y: "100%" }} transition={{ delay: 0.5, duration: 0.5 }}
                className='text-6xl text-center lg:text-right lg:text 9xl'>
            Angel Ramirez
          </m.h1>
          <div className='h-50 w-50'>
            
          </div>
        </div>
        
        <div className='flex justify-between'>
          <div>
          <h2>Developer</h2>
          <h2>Portfolio</h2>
          </div>
          <m.div variants={container} initial="hidden" animate="show">
            <m.h3 varients={item} >Dynamic and interactive content</m.h3>
            <m.h3 varients={item}>Professional grade & quality driven work</m.h3>
            <m.h3 varients={item}>UI & UX meeting industry standard</m.h3>
          </m.div>
        </div>
      </main>
    </m.div>
  );
  }
      