import Head from 'next/head'
import { motion as m } from 'framer-motion'

export default function Home() {
  return (
    <m.div 
    initial={{ y: "100%" }}
    animate={{ y: "0%" }}
    transition={{ duration: 0.75, ease: "easeOut" }}
    exit={{ opacity: 1, }}
    className="text-grey-900 absolute top-0 left-0 w-full h-full bg-orange-100 lg:px-48 px-16"
    >
      <Head>
        <title>Angel Ramirez | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='my-96 p-1'>
          <h1 className='text-6xl text-center lg:text-right lg:text 9xl'>
            Angel Ramirez
          </h1>
        </div>
        
        <div className='flex justify-between'>
          <div>
          <h2>Front-End</h2>
          <h2>Developer</h2>
          <h2>Portfolio</h2>
          </div>
          <div>
            <h3>Dynamic and interactive content</h3>
            <h3>Professional grade & quality driven work</h3>
            <h3>UI & UX meeting industry standard</h3>
          </div>
        </div>
      </main>
    </m.div>
  );
  }
      